### GET hero
GET http://localhost:8080/hero/hero

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### save hero
POST http://localhost:8080/hero
Content-Type: application/json

{
  "name": "hero100",
  "title": "title100"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### GET hero
GET http://localhost:8080/hero/laxmi

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}