spring:
  application:
    name: sb402learn1
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    export:
      enabled: false
  logging:
    export:
      otlp:
        enabled: false
  appoptics:
    metrics:
      export:
        enabled: false